# Generated by Django 5.2.7 on 2025-11-02 18:28

from django.db import migrations

def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    from phonenumbers import parse, format_number, PhoneNumberFormat, NumberParseException, is_valid_number

    for flat in Flat.objects.iterator():
        if flat.owners_phonenumber:
            try:
                parsed = parse(flat.owners_phonenumber, "RU")
                if is_valid_number(parsed):
                    flat.owner_pure_phone = format_number(parsed, PhoneNumberFormat.E164)
                else:
                    flat.owner_pure_phone = None
            except NumberParseException:
                flat.owner_pure_phone = None
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone),
    ]
