# Generated by Django 5.2.7 on 2025-11-05 16:52

from django.db import migrations


def copy_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        if not (flat.owner or flat.owner_pure_phone or
                flat.owners_phonenumber):
            continue


        owner_object, created = Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                'phonenumber': flat.owners_phonenumber,
                'pure_phone': flat.owner_pure_phone,
            }
        )

        if not created:
           if not owner_object.phonenumber:
               owner_object.phonenumber = flat.owners_phonenumber
           if not owner_object.pure_phone:
               owner_object.pure_phone = flat.owner_pure_phone
           owner_object.save()


def reverse_copy_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [migrations.RunPython(copy_owners, reverse_copy_owners),
    ]