# Generated by Django 5.2.7 on 2025-11-05 19:09

from django.db import migrations


def link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        if not (flat.owner or flat.owner_pure_phone or
                flat.owners_phonenumber):
            continue

        owner_object, _ = Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                'phonenumber': flat.owners_phonenumber,
                'pure_phone': flat.owner_pure_phone,
            }
        )

        owner_object.flats.add(flat)


def reverse_link_owners_to_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_copy_flat_owners_to_owner'),
    ]

    operations = [migrations.RunPython(link_owners_to_flats, reverse_link_owners_to_flats),
    ]
